CREATE TABLE "GCG_6153_HIST_INSP"(
"HIST_ID" IDENTITY,
"JOB" CHAR(6),
"SUFFIX" CHAR(3),
"SEQ" CHAR(6),
"KEY_SEQ" INTEGER,
"WORKCENTER" CHAR(4),
"PART" CHAR(20),
"SERIAL_NUMBER" CHAR(30),
"COMMENT" CHAR(100),
"STATUS" CHAR(15),
"CATEGORY" CHAR(20),
"EMPLOYEE" CHAR(5),
"INSP_BY" CHAR(30),
"INSP_DATE" DATETIME;

CREATE INDEX "GCG_6153_HIST_INSP" ON "GCG_6153_HIST_INSP"("HIST_ID", "JOB", "SUFFIX","SEQ","PART");
 